#!/bin/bash

#source /opt/Xilinx/SDK/2018.1/settings64.sh

pushd $ROOTPATH/images/Embedded

/opt/Xilinx/SDK/2018.1/bin/program_flash \
    -f BOOT.mcs \
    -offset 0 \
    -fsbl TW_Imag_fsbl_0.elf \
    -flash_type qspi_single \
    -cable type xilinx_tcf url TCP:127.0.0.1:3121

#     -blank_check
#     -verify \

popd
