#!/usr/bin/python3
import os
import sys

from PIL import Image


class ConvertPicture:

    def __init__(self, fpath):
        if not os.path.exists(fpath):
            raise FileExistsError('Not Exists: {}'.format(fpath))
        self.filepath = fpath
        self.im = Image.open(fpath).convert('RGBA')
        self.pixels = self.im.load()
        self.width, self.height = self.im.size

    def to_ARGB(self, ):
        with open(self.filepath+".argb", "wb") as f:
            for y in range(self.height):
                argb = bytearray()
                for x in range(self.width):
                    v = self.pixels[x, y]
                    #                    PC
                    argb.append(v[2])  # B
                    argb.append(v[1])  # G
                    argb.append(v[0])  # R
                    # argb.append(v[3])
                    argb.append(0x64)
                f.write(argb)


def usage():
    '''
Usage: {pgm} <image_file>
    '''
    print(usage.__doc__.format(pgm=sys.argv[0].split('/')[-1]))
    raise SystemExit(1)


if __name__ == '__main__':
    if len(sys.argv) < 2:
        usage()

    ConvertPicture(sys.argv[1]).to_ARGB()
